### ISSUE TITLE
Add More Arithmetic Operators

### ISSUE THREAD

**Issue by bhudgeons** [batman-nair/IRCIS#4]
I'm adding more arithmetic operators, but wanted @batman-nair's opinion on something:

The new operators are pretty straightforward and standard:

```& bitwise AND
| bitwise OR
< bitwise left shift
> bitwise right shift
```

But I'm not sure about exponentiation and XOR. In C, ^ is XOR, but to the general public 2^3 is usually "2 to the third power," and I think we should use that in IRCIS. But then, what do we use for XOR? 

Some candidates:
V
$

and while I'd like to keep it ASCII, there's also

U+22BB ⊻ XOR (HTML &#8891;) 
U+2295 ⊕ CIRCLED PLUS (HTML &#8853; · &oplus;)

**Comment by bhudgeons** [comment]
I used V for XOR ... it looks kinda like the XOR unicode symbol. [Julia used to use $](https://groups.google.com/forum/#!msg/julia-dev/81EBHweEf88/-ul-Slu02FIJ). I could go either way, but would like to keep it ASCII.

**Comment by batman-nair** [comment]
Cool! 
Yeah, it's better to keep things ASCII...
V should be fine for XOR, $ feels out of place/weird.

**Comment by bhudgeons** [comment]
Sounds good ... I added the tests, but I didn't add the stuff in the tests to the demo in the README ... not sure if it is a good idea. The existing demo is clear & simple.

**Comment by batman-nair** [comment]
Yeah, adding to the commands table should be enough. 
Better to keep things as simple as possible.
