### ISSUE TITLE
Making options handling clean

### ISSUE THREAD

**Issue by batman-nair** [batman-nair/IRCIS#6]
Hey @bhudgeons,

I was thinking about using [cxxopts](https://github.com/jarro2783/cxxopts) for making options handling a lot easier and making main function cleaner.
Since you were the one that implemented it, wanted to know your opinion.
You can find the changes in develop branch.

**Comment by bhudgeons** [comment]
Certainly fine with me ... I'm happy with anything that makes stuff cleaner.
